// <auto-generated />
using System;
using ISIncidentTracker.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISIncidentTracker.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511215344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DATA_LEAK",
                            Description = "Несанкционированная передача конфиденциальной информации",
                            Name = "Утечка данных"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DDOS",
                            Description = "Атака типа 'отказ в обслуживании'",
                            Name = "DDoS-атака"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MALWARE",
                            Description = "Обнаружение вирусов, троянов, шпионского ПО",
                            Name = "Вредоносное ПО"
                        },
                        new
                        {
                            Id = 4,
                            Code = "UNAUTH_ACCESS",
                            Description = "Попытка или факт несанкционированного входа",
                            Name = "Несанкционированный доступ"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PHISHING",
                            Description = "Попытка получения учетных данных через социальную инженерию",
                            Name = "Фишинг"
                        });
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OccurredDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReportedById");

                    b.HasIndex("ReportedDate");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Viewer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 11, 21, 53, 43, 795, DateTimeKind.Utc).AddTicks(9544),
                            Email = "admin@is-tracker.local",
                            FullName = "Администратор Системы",
                            IsActive = true,
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 11, 21, 53, 43, 795, DateTimeKind.Utc).AddTicks(9546),
                            Email = "analyst@is-tracker.local",
                            FullName = "Аналитик ИБ",
                            IsActive = true,
                            Role = "Analyst",
                            Username = "analyst"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 11, 21, 53, 43, 795, DateTimeKind.Utc).AddTicks(9548),
                            Email = "viewer@is-tracker.local",
                            FullName = "Наблюдатель",
                            IsActive = true,
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Incident", b =>
                {
                    b.HasOne("ISIncidentTracker.Web.Models.User", "AssignedTo")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Incidents_Users_AssignedTo");

                    b.HasOne("ISIncidentTracker.Web.Models.Category", "Category")
                        .WithMany("Incidents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Incidents_Categories");

                    b.HasOne("ISIncidentTracker.Web.Models.User", "ReportedBy")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Incidents_Users_ReportedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Category", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.User", b =>
                {
                    b.Navigation("AssignedIncidents");

                    b.Navigation("ReportedIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
