// <auto-generated />
using System;
using ISIncidentTracker.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISIncidentTracker.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PHISHING",
                            Description = "Фишинговые атаки и поддельные письма",
                            Name = "Фишинг"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DATA_LEAK",
                            Description = "Компрометация или утечка конфиденциальных данных",
                            Name = "Утечка данных"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DDOS",
                            Description = "Распределённая атака типа 'отказ в обслуживании'",
                            Name = "DDoS-атака"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MALWARE",
                            Description = "Вирусы, трояны, шпионское ПО, ботнеты",
                            Name = "Вредоносное ПО"
                        },
                        new
                        {
                            Id = 5,
                            Code = "RANSOMWARE",
                            Description = "Шифровальщики и программы-вымогатели",
                            Name = "Ransomware"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UNAUTH_ACCESS",
                            Description = "Попытка или факт несанкционированного входа в систему",
                            Name = "Несанкционированный доступ"
                        },
                        new
                        {
                            Id = 7,
                            Code = "DEVICE_LOSS",
                            Description = "Утеря или кража корпоративного устройства",
                            Name = "Потеря устройства"
                        },
                        new
                        {
                            Id = 8,
                            Code = "POLICY_VIOLATION",
                            Description = "Нарушение внутренних правил ИБ",
                            Name = "Нарушение политик безопасности"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SQLI",
                            Description = "Атаки внедрением вредоносного SQL-кода",
                            Name = "SQL Injection"
                        },
                        new
                        {
                            Id = 10,
                            Code = "XSS",
                            Description = "Межсайтовый скриптинг и инъекции кода",
                            Name = "XSS атака"
                        },
                        new
                        {
                            Id = 11,
                            Code = "SOCIAL_ENG",
                            Description = "Манипулирование персоналом для получения доступа",
                            Name = "Социальная инженерия"
                        },
                        new
                        {
                            Id = 12,
                            Code = "OTHER",
                            Description = "Инциденты, не подпадающие под другие категории",
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OccurredDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReportedById");

                    b.HasIndex("ReportedDate");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.IncidentTag", b =>
                {
                    b.Property<int>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IncidentId", "TagId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TagId");

                    b.ToTable("IncidentTags");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Требует немедленного внимания",
                            Name = "Срочно"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Затрагивает клиентские данные",
                            Name = "Клиент"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Внутренний инцидент",
                            Name = "Внутренний"
                        });
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Viewer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 12, 10, 3, 42, 697, DateTimeKind.Utc).AddTicks(4939),
                            Email = "admin@is-tracker.local",
                            FullName = "Администратор Системы",
                            IsActive = true,
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 12, 10, 3, 42, 697, DateTimeKind.Utc).AddTicks(4941),
                            Email = "analyst@is-tracker.local",
                            FullName = "Аналитик ИБ",
                            IsActive = true,
                            Role = "Analyst",
                            Username = "analyst"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 12, 10, 3, 42, 697, DateTimeKind.Utc).AddTicks(4942),
                            Email = "viewer@is-tracker.local",
                            FullName = "Наблюдатель",
                            IsActive = true,
                            Role = "Viewer",
                            Username = "viewer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 12, 10, 3, 42, 697, DateTimeKind.Utc).AddTicks(4943),
                            Email = "soc@is-tracker.local",
                            FullName = "Оператор SOC",
                            IsActive = true,
                            Role = "Analyst",
                            Username = "soc_operator"
                        });
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Incident", b =>
                {
                    b.HasOne("ISIncidentTracker.Web.Models.User", "AssignedTo")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Incidents_Users_AssignedToId");

                    b.HasOne("ISIncidentTracker.Web.Models.Category", "Category")
                        .WithMany("Incidents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Incidents_Categories_CategoryId");

                    b.HasOne("ISIncidentTracker.Web.Models.User", "ReportedBy")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Incidents_Users_ReportedById");

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.IncidentTag", b =>
                {
                    b.HasOne("ISIncidentTracker.Web.Models.Incident", "Incident")
                        .WithMany("IncidentTags")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IncidentTags_Incidents");

                    b.HasOne("ISIncidentTracker.Web.Models.Tag", "Tag")
                        .WithMany("IncidentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IncidentTags_Tags");

                    b.Navigation("Incident");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Category", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Incident", b =>
                {
                    b.Navigation("IncidentTags");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.Tag", b =>
                {
                    b.Navigation("IncidentTags");
                });

            modelBuilder.Entity("ISIncidentTracker.Web.Models.User", b =>
                {
                    b.Navigation("AssignedIncidents");

                    b.Navigation("ReportedIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
